<a href="https://colab.research.google.com/github/udayanjansai/Numpy_Operations/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install numpy


In [3]:
import numpy as np

In [4]:
arr1=np.array([1,2,3])
print(arr1)

[1 2 3]


In [8]:
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)
print(np.ndim(arr2))
np.zeros((3,4))

[[1 2 3]
 [4 5 6]]
2


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
ones=np.ones((2,2))
print(ones)

[[1. 1.]
 [1. 1.]]


In [10]:
rand=np.random.random((2,2))
print(rand)

[[0.13889596 0.69110013]
 [0.91752878 0.468166  ]]


In [12]:
identity=np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
aran=np.arange(0,10,2)
print(aran)
#arange(start,stop,step)

[0 2 4 6 8]


In [17]:
lin=np.linspace(1,5,9)
print(lin)
#linspace(start,stop,no of points)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]


In [29]:
print(np.full((3),4))

[4 4 4]


In [30]:
print(np.empty((3,2)))

[[2.e-323 2.e-323]
 [2.e-323 2.e-323]
 [2.e-323 2.e-323]]


In [31]:
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
print("sizze:",b.size)
print("dim",b.shape)
print("data type",b.dtype)
print("no of dim:",b.ndim)

sizze: 6
dim (2, 3)
data type float64
no of dim: 2


In [48]:
temp_data=np.array([(24,26,22),(30,28,27)])
print(temp_data)
print("shape:",temp_data.shape)
print("size:",temp_data.size)
print("data type:",temp_data.dtype)
print("no of dim:",temp_data.ndim)

[[24 26 22]
 [30 28 27]]
shape: (2, 3)
size: 6
data type: int64
no of dim: 2


In [49]:
third=np.array([21, 23, 22])
np.append(temp_data,third)
#temp_data.append(third)
temp_data=np.vstack((temp_data,third))
print(temp_data)

[[24 26 22]
 [30 28 27]
 [21 23 22]]


In [59]:
updated_temp_data=temp_data
sensor_error_flag=np.zeros((2,3),dtype=int)
print(sensor_error_flag)
greenhouse_identity=np.identity(3,dtype=int)
print(greenhouse_identity)

[[0 0 0]
 [0 0 0]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [67]:
print(temp_data[0,:])

[24 26 22]


Indexing and Slicing:
You are working as a Data Analyst at a fruit distribution company.

The company stores the number of fruit boxes shipped per day (for 1 week) in a 2D NumPy array where:
Each row represents a type of fruit.
Each column represents a day of the week (Mon–Sun).


Your Tasks
Create the 2D NumPy array

Create an array named shipments using the above data.
Access single elements (Indexing):
Get the number of Apples shipped on Wednesday.
Get the number of Oranges shipped on Sunday.
Access multiple elements (Slicing):
Extract all the weekday shipments (Mon–Fri) for all fruits.
Extract only the weekend shipments (Sat & Sun).
Extract the shipments of Apples from Wednesday to Saturday.
Bonus (Practice thinking):
Replace the Saturday shipment of Apples (currently 80) with 100 using indexing.


In [70]:
week=np.array(['mon','tue','wed','thu','fri','sat','sun'],dtype=str)
print(week)

['mon' 'tue' 'wed' 'thu' 'fri' 'sat' 'sun']


In [71]:
app=np.array([40,30,20,40,50,60,70])
ban=np.array([50,60,40,30,60,70,80])
ora=np.array([10,20,30,40,50,60,70])
shipments=np.vstack((week,app,ban,ora))
print(shipments)

[['mon' 'tue' 'wed' 'thu' 'fri' 'sat' 'sun']
 ['40' '30' '20' '40' '50' '60' '70']
 ['50' '60' '40' '30' '60' '70' '80']
 ['10' '20' '30' '40' '50' '60' '70']]


In [79]:
print("number of Apples shipped on Wednesday.",shipments[1,2])
print("number of Oranges shipped on Sunday.",shipments[3,6])
print("all the weekday shipments (Mon–Fri) for all fruits.\n",shipments[1:,:5])
print("Extract only the weekend shipments (Sat & Sun).\n",shipments[1:,5:])
print("Extract the shipments of Apples from Wednesday to Saturday.\n",shipments[1,2:6])
shipments[1,5]=100
print(shipments)

number of Apples shipped on Wednesday. 20
number of Oranges shipped on Sunday. 70
all the weekday shipments (Mon–Fri) for all fruits.
 [['40' '30' '20' '40' '50']
 ['50' '60' '40' '30' '60']
 ['10' '20' '30' '40' '50']]
Extract only the weekend shipments (Sat & Sun).
 [['100' '70']
 ['70' '80']
 ['60' '70']]
Extract the shipments of Apples from Wednesday to Saturday.
 ['20' '40' '50' '100']
[['mon' 'tue' 'wed' 'thu' 'fri' 'sat' 'sun']
 ['40' '30' '20' '40' '50' '100' '70']
 ['50' '60' '40' '30' '60' '70' '80']
 ['10' '20' '30' '40' '50' '60' '70']]


In [85]:
#arithmetic operations
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a*2)
print(np.dot(a,b))

#broadcasting
c=3
print("broadcasting of a and c\n",a+c)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[2 4 6]
32
broadcasting of a and c
 [4 5 6]


In [90]:
#universal functions
# 1. Arithmetic ufuncs
# Operate element-wise on arrays.
# np.add(x, y)
# np.subtract(x, y)
# np.multiply(x, y)
# np.divide(x, y)
# np.power(x, y)
# np.mod(x, y)
# 🔹 2. Exponential and Logarithmic ufuncs
# (You already covered these)
# np.exp(x)
# np.log(x)
# np.log10(x)
# np.log2(x)
# np.expm1(x)    # exp(x) - 1
# 🔹 3. Trigonometric ufuncs
# np.sin(x)
# np.cos(x)
# np.tan(x)
# np.arcsin(x)
# np.arccos(x)
# np.arctan(x)
# np.degrees(x)
# np.radians(x)
# 🔹 4. Rounding ufuncs
# np.round(x)
# np.floor(x)
# np.ceil(x)
# np.trunc(x)
# 🔹 5. Statistical ufuncs
# (Operate along an axis or entire array)
# np.min(x)
# np.max(x)
# np.mean(x)
# np.std(x)
# np.var(x)
# np.sum(x)
# np.prod(x)
# 🔹 6. Logical ufuncs
# np.logical_and(x, y)
# np.logical_or(x, y)
# np.logical_not(x)
# np.logical_xor(x, y)
# 🔹 7. Comparison ufuncs
# (Return Boolean arrays)
# np.greater(x, y)
# np.less(x, y)
# np.equal(x, y)
# np.not_equal(x, y)
# np.greater_equal(x, y)
# np.less_equal(x, y)
# 🔹 8. Bitwise ufuncs
# (Operate on integers)
# np.bitwise_and(x, y)
# np.bitwise_or(x, y)
# np.bitwise_xor(x, y)
# np.invert(x)
d=np.array([1,2,3])
e=np.array([4,5,6])
print(np.power(d,e))
print(np.mod(e,d))
print(np.exp(d))
print(np.sqrt(d))
print(np.log(d))

[  1  32 729]
[0 1 0]
[ 2.71828183  7.3890561  20.08553692]
[1.         1.41421356 1.73205081]
[0.         0.69314718 1.09861229]


In [96]:
# 2. Exponential and Logarithmic ufuncs
print(np.exp(d))
print(np.log(d))
print(np.log10(d))
print(np.log2(d))
print(np.expm1(d))

[ 2.71828183  7.3890561  20.08553692]
[0.         0.69314718 1.09861229]
[0.         0.30103    0.47712125]
[0.        1.        1.5849625]
[ 1.71828183  6.3890561  19.08553692]


In [209]:
 #Trigonometric ufuncs
print(np.sin(d))
print(np.cos(d))
print(np.tan(d))
print(np.arcsin(d))
print(np.arccos(d))
print(np.arctan(d))


[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[ 1.55740772 -2.18503986 -0.14254654]
[1.57079633        nan        nan]
[ 0. nan nan]
[0.78539816 1.10714872 1.24904577]


/tmp/ipython-input-2568417770.py:5: RuntimeWarning: invalid value encountered in arcsin
  print(np.arcsin(d))
/tmp/ipython-input-2568417770.py:6: RuntimeWarning: invalid value encountered in arccos
  print(np.arccos(d))


In [100]:
#statistics
x=np.array([30,80,3000])
y=np.array([4,5,6])
print(np.min(x))
print(np.max(x))
np.mean(x)
np.std(x)
np.var(x)
np.sum(x)
np.prod(x)

np.int64(7200000)

Create arrays
Create three 2D NumPy arrays farmA, farmB, farmC (each shape (4,3)).
Stack them into a single 3D array production_all of shape (3, 4, 3).
Array attributes
Print the .shape, .size, .dtype, and .ndim of production_all.
Per-farm totals (arithmetic & aggregation)
Use aggregation ufuncs to compute the total energy per farm (sum across panels & hours) → total_per_farm (shape (3,)).
Compute mean, std, and var per farm.
Per-hour matrix multiplication idea (matrix op)
For a quick weighted estimate, create a hour_weights row vector of shape (3,) = [0.5, 1.0, 0.75] (weights for hour1, hour2, hour3).
Compute weighted_per_panel by performing a dot product between each farm's panel-row and hour_weights to get per-panel weighted energy. (Use np.dot / matrix multiplication appropriately.)
Broadcasting adjustments
The operator notices a fixed calibration offset of +0.5 kWh for all panels in Farm B. Use broadcasting to add this offset to Farm B data inside production_all (without recreating whole array manually).
Element-wise arithmetic (ufuncs: add/sub/mul/div/power/mod)
Compute a normalized version where you:
subtract the per-farm mean (use broadcasting),
divide by the per-farm std (broadcasting) — i.e., z-score normalize each farm's panel-hour readings.
Apply many ufuncs (use the ufuncs listed previously)
Apply the following element-wise operations (create variables for each) on the normalized data (or a copy) and show the resulting arrays (or summaries — shape/dtype/first row) where appropriate:
Exponential family: np.exp, np.expm1, np.log (note: handle non-positive inputs if needed), np.log10, np.log2.
Trigonometric: np.sin, np.cos, np.tan, np.arcsin, np.arccos, np.arctan, plus np.degrees, np.radians applied appropriately.
Rounding: np.round, np.floor, np.ceil, np.trunc.
Comparison & logical ufuncs: create a boolean mask high_output = production_all > 20 and apply np.logical_and, np.logical_or, np.logical_not, np.logical_xor combining masks (e.g., high_output and even_hours_mask). Also use comparison ufuncs like np.greater_equal, np.less.
Bitwise ufuncs (on integer arrays): create an integer array alerts = np.array([[1,0,1],[0,0,1],[1,1,0],[0,1,0]]) for each farm (shape match required) — then apply np.bitwise_and, np.bitwise_or, np.invert where sensible.
Arithmetic ufuncs again: np.add, np.subtract, np.multiply, np.divide, np.power, np.mod.
Aggregations over ufunc outputs: e.g., np.sum(np.exp(...)), np.mean(np.sin(...)).
Broadcast-based summary table
Use broadcasting to compute a (3,4) array panel_totals_per_farm = total per panel (sum across hours for each panel), and then compute a (3,) boolean needs_maintenance saying True if any panel in that farm has total < 40. Use np.min, np.max, np.any, np.all.
Final KPIs (aggregation)
Compute:
overall_total (sum of all farms),
peak_hour value (max across hours) and which farm & panel produced it (use np.argmax with careful unraveling),
average_per_panel across all farms.

In [104]:
farma=np.array([[20,30,25],[23,26,28],[28,26,29],[22,29,26]])
farmb=np.array([(24,22,24),(27,26,24),(25,24,23),[27,30,26]])
farmc=np.array([(22,25,27),(22,26,24),(26,27,28),[24,25,26]])
prodction=np.array([farma,farmb,farmc])
print(prodction)
print("shape:",prodction.shape)
print("size:",prodction.size)
print("data type:",prodction.dtype)
print("no of dim:",prodction.ndim)

[[[20 30 25]
  [23 26 28]
  [28 26 29]
  [22 29 26]]

 [[24 22 24]
  [27 26 24]
  [25 24 23]
  [27 30 26]]

 [[22 25 27]
  [22 26 24]
  [26 27 28]
  [24 25 26]]]
shape: (3, 4, 3)
size: 36
data type: int64
no of dim: 3


In [109]:
resa=np.sum(farma,axis=0)
print("production of farm A:",resa)
resb=np.sum(farmb,axis=0)
print("production of farm B:",resb)
resc=np.sum(farmc,axis=0)
print("production of farm C:",resc)

production of farm A: [ 93 111 108]
production of farm B: [103 102  97]
production of farm C: [ 94 103 105]


In [124]:
# Compute mean, std, and var per farm.
print("farma mean,std,var\n")
print("mean:",np.mean(farma))
print("std:",np.std(farma))
print("var:",np.var(farma))
print("\nfarmb mean,std,var\n")
print("mean:",np.mean(farmb))
print("std:",np.std(farmb))
print("var:",np.var(farmb))
print("\nfarmc mean,std,var\n")
print("mean:",np.mean(farmc))
print("std:",np.std(farmc))
print("var:",np.var(farmc))

farma mean,std,var

mean: 26.0
std: 2.943920288775949
var: 8.666666666666666

farmb mean,std,var

mean: 25.166666666666668
std: 2.0749832663314556
var: 4.305555555555556

farmc mean,std,var

mean: 25.166666666666668
std: 1.818118685772619
var: 3.305555555555556


In [128]:
hour_weights=np.array([0.5, 1.0, 0.75])
print("\nweighted_per_panel for farmA\n")
print(np.dot(farma,hour_weights))
print("\nweighted_per_panel for farmB\n")
print(np.dot(farmb,hour_weights))
print("\nweighted_per_panel for farmC\n")
print(np.dot(farmc,hour_weights))


weighted_per_panel for farmA

[58.75 58.5  61.75 59.5 ]

weighted_per_panel for farmB

[52.   57.5  53.75 63.  ]

weighted_per_panel for farmC

[56.25 55.   61.   56.5 ]


In [133]:
# Broadcasting adjustments
# The operator notices a fixed calibration offset of +0.5 kWh for all panels in Farm B. Use broadcasting to add this offset to Farm B data inside production_all
# (without recreating whole array manually).
print(prodction)
prodction[1]=prodction[1]+0.5
print(prodction)

[[[20 30 25]
  [23 26 28]
  [28 26 29]
  [22 29 26]]

 [[24 22 24]
  [27 26 24]
  [25 24 23]
  [27 30 26]]

 [[22 25 27]
  [22 26 24]
  [26 27 28]
  [24 25 26]]]
[[[20 30 25]
  [23 26 28]
  [28 26 29]
  [22 29 26]]

 [[24 22 24]
  [27 26 24]
  [25 24 23]
  [27 30 26]]

 [[22 25 27]
  [22 26 24]
  [26 27 28]
  [24 25 26]]]


In [140]:
# Element-wise arithmetic (ufuncs: add/sub/mul/div/power/mod)
# Compute a normalized version where you:
# subtract the per-farm mean (use broadcasting),
# divide by the per-farm std (broadcasting) — i.e., z-score normalize each farm's panel-hour readings.
mea1=np.mean(prodction[0])
mea2=np.mean(prodction[1])
mea3=np.mean(prodction[2])
normpro1=prodction[0]-mea1
normpro2=prodction[1]-mea2
normpro3=prodction[2]-mea3
normproduction=np.array([normpro1,normpro2,normpro3])
print(normproduction)
std1=np.std(prodction[0])
std2=np.std(prodction[1])
std3=np.std(prodction[2])
stdpro1=prodction[0]/std1
stdpro2=prodction[2]/std2
stdpro3=prodction[2]/std3
stdproduction=np.array([stdpro1,stdpro2,stdpro3])
print(stdproduction)

[[[-6.          4.         -1.        ]
  [-3.          0.          2.        ]
  [ 2.          0.          3.        ]
  [-4.          3.          0.        ]]

 [[-1.16666667 -3.16666667 -1.16666667]
  [ 1.83333333  0.83333333 -1.16666667]
  [-0.16666667 -1.16666667 -2.16666667]
  [ 1.83333333  4.83333333  0.83333333]]

 [[-3.16666667 -0.16666667  1.83333333]
  [-3.16666667  0.83333333 -1.16666667]
  [ 0.83333333  1.83333333  2.83333333]
  [-1.16666667 -0.16666667  0.83333333]]]
[[[ 6.7936622  10.19049331  8.49207776]
  [ 7.81271154  8.83176087  9.51112709]
  [ 9.51112709  8.83176087  9.8508102 ]
  [ 7.47302843  9.8508102   8.83176087]]

 [[10.60249514 12.04828993 13.01215313]
  [10.60249514 12.53022153 11.56635834]
  [12.53022153 13.01215313 13.49408473]
  [11.56635834 12.04828993 12.53022153]]

 [[12.10042016 13.75047746 14.85051565]
  [12.10042016 14.30049655 13.20045836]
  [14.30049655 14.85051565 15.40053475]
  [13.20045836 13.75047746 14.30049655]]]


In [144]:
mean_per_farm  = np.mean(prodction, axis=(1,2))
std_per_farm   = np.std(prodction, axis=(1,2))
print(mean_per_farm)
print(std_per_farm)
norm_data = (prodction - mean_per_farm[:, None, None]) / std_per_farm[:, None, None]
print("Normalized data (z-score):\n", np.round(norm_data[0], 2))  # show first farm example
print(norm_data)

[26.         25.16666667 25.16666667]
[2.94392029 2.07498327 1.81811869]
Normalized data (z-score):
 [[-2.04  1.36 -0.34]
 [-1.02  0.    0.68]
 [ 0.68  0.    1.02]
 [-1.36  1.02  0.  ]]
[[[-2.03809866  1.35873244 -0.33968311]
  [-1.01904933  0.          0.67936622]
  [ 0.67936622  0.          1.01904933]
  [-1.35873244  1.01904933  0.        ]]

 [[-0.56225353 -1.52611672 -0.56225353]
  [ 0.88354126  0.40160966 -0.56225353]
  [-0.08032193 -0.56225353 -1.04418513]
  [ 0.88354126  2.32933605  0.40160966]]

 [[-1.74172714 -0.09166985  1.00836835]
  [-1.74172714  0.45834925 -0.64168895]
  [ 0.45834925  1.00836835  1.55838744]
  [-0.64168895 -0.09166985  0.45834925]]]


In [ ]:
exp_data    = np.exp(norm_data)
expm1_data  = np.expm1(norm_data)
log_data    = np.log(np.abs(norm_data) + 1)  # avoid negatives
log10_data  = np.log10(np.abs(norm_data) + 1)
log2_data   = np.log2(np.abs(norm_data) + 1)

sin_data = np.sin(norm_data)
cos_data = np.cos(norm_data)
tan_data = np.tan(norm_data)

arcsin_data  = np.arcsin(np.clip(sin_data, -1, 1))
arccos_data  = np.arccos(np.clip(cos_data, -1, 1))
arctan_data  = np.arctan(norm_data)

degrees_data = np.degrees(arctan_data)
radians_data = np.radians(degrees_data)

round_data = np.round(norm_data)
floor_data = np.floor(norm_data)
ceil_data  = np.ceil(norm_data)
trunc_data = np.trunc(norm_data)

# Just show shapes / samples
print("exp_data shape:", exp_data.shape)
print("sin_data[0]:\n", np.round(sin_data[0], 2))
print()


In [ ]:
# 9️⃣ Logical & comparison masks
# -------------------------------
high_output = prodction > 20
even_hours_mask = (np.arange(3) % 2 == 0)[None, None, :]
and_mask  = np.logical_and(high_output, even_hours_mask)
or_mask   = np.logical_or(high_output, even_hours_mask)
not_mask  = np.logical_not(high_output)
xor_mask  = np.logical_xor(high_output, even_hours_mask)

greater_equal = np.greater_equal(prodction, 18)
less_than     = np.less(prodction, 12)

print("High output mask (sample farm):\n", high_output[2])
print()


In [ ]:
#Bitwise operations
# -------------------------------
alerts = np.array([
    [[1,0,1],
     [0,0,1],
     [1,1,0],
     [0,1,0]],
    [[1,0,1],
     [0,0,1],
     [1,1,0],
     [0,1,0]],
    [[1,0,1],
     [0,0,1],
     [1,1,0],
     [0,1,0]]
], dtype=int)

bit_and = np.bitwise_and(alerts, (prodction > 18))
bit_or  = np.bitwise_or(alerts, (prodction > 18))
bit_not = np.invert(alerts)

print("Bitwise AND sample:\n", bit_and[0])
print()


In [ ]:
add_data = np.add(prodction, 1)
sub_data = np.subtract(prodction, 1)
mul_data = np.multiply(prodction, 2)
div_data = np.divide(prodction, 2)
pow_data = np.power(prodction, 2)
mod_data = np.mod(prodction, 5)

print("Example np.multiply output (FarmA):\n", mul_data[0])
print()

# Aggregations
sum_exp = np.sum(np.exp(norm_data))
mean_sin = np.mean(np.sin(norm_data))
print("Sum of exp(norm):", sum_exp)
print("Mean of sin(norm):", mean_sin)
print()


In [ ]:
panel_totals_per_farm = np.sum(prodction, axis=2)  # (3,4)
needs_maintenance = np.any(panel_totals_per_farm < 40, axis=1)

print("Panel totals per farm:\n", panel_totals_per_farm)
print("Needs maintenance:", needs_maintenance)
print()

In [ ]:
overall_total = np.sum(prodction)
peak_value = np.max(prodction)
peak_index = np.unravel_index(np.argmax(prodction), prodction.shape)
average_per_panel = np.mean(prodction, axis=(0,2))  # avg per panel index across farms

print("Overall total energy:", overall_total)
print("Peak hour value:", peak_value)
print(f"Peak at: Farm {peak_index[0]}, Panel {peak_index[1]}, Hour {peak_index[2]}")
print("Average per panel across farms:", average_per_panel)

In [145]:
#reshaping
arr=np.array([1,2,3,4,5])
reshaped=arr.reshape(5,1)
print(reshaped)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [161]:
#stacking and ssplitting
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
vstacked=np.vstack((arr1,arr2))
print(vstacked)
hstacked=np.hstack((arr1,arr2))
print(hstacked)
stack=np.stack((arr1,arr2),axis=1)
print(stack)
arr3=np.array([1,2,3,4,56,7,8,9,10])
split=np.split(arr3,3)
print(split)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1 4]
 [2 5]
 [3 6]]
[array([1, 2, 3]), array([ 4, 56,  7]), array([ 8,  9, 10])]


In [168]:
#boolean and fancy indexing
print(arr3[arr3>10])
indices=[0,3,4,6]
print(arr3[indices])

[56]
[ 1  4 56  8]


In [170]:
#view and copy
arr4=np.array([1,2,3,4,5])
view=arr4.view()
view[0]=10
print(view)
copy=arr4.copy()
copy[0]=20
print(arr4)
print(copy)

[10  2  3  4  5]
[10  2  3  4  5]
[20  2  3  4  5]


In [173]:
#saving and loading
arr5=np.array([1,2,3,4,5])
np.save("arr5.npy",arr5)
loaded=np.load("arr5.npy")
print(loaded)

[1 2 3 4 5]


In [174]:
load=np.load("arr5.npy")
print(load)

[1 2 3 4 5]


TasksArray Creation
Create a 1D array of numbers from 10 to 50.
Create a 3x3 array of random numbers between 0 and 1.
Array Attributes
Find the shape, size, and data type of the array you created in the previous task.
Basic Operations
Add 5 to every element of a 1D array.
Multiply two 2D arrays element-wise.
Indexing and Slicing
Create a 5x5 array of integers from 1 to 25. Extract:
The first row.
The last column.
A subarray of the first three rows and first two columns.
Aggregation
Create a 10-element array of random integers between 10 and 100. Find:
The maximum value.
The minimum value.
The mean and standard deviation.
Reshaping
Convert a 1D array of numbers from 1 to 12 into a 3x4 matrix.
Broadcasting
Create a 3x3 matrix of ones. Add a 1D array [1, 2, 3] to each row.
Filtering
Create a 1D array of random integers between 1 and 50. Extract all elements that are divisible by 5.
Matrix Multiplication
Create two 2x2 matrices and perform matrix multiplication.
Advanced Indexing
Given a 4x4 array, use fancy indexing to extract the diagonal elements.

In [178]:
# Create a 1D array of numbers from 10 to 50.
ar1=np.arange(10,51)
print(ar1)
ar2=np.random.random((3,3))
print(ar2)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
[[0.40107321 0.72675683 0.86674511]
 [0.49313524 0.67137634 0.30383886]
 [0.73366275 0.61895388 0.48692072]]


In [179]:
print("shape:",ar2.shape)
print("size:",ar2.size)
print("data type:",ar2.dtype)
print("no of dim:",ar2.ndim)

shape: (3, 3)
size: 9
data type: float64
no of dim: 2


In [182]:
# Add 5 to every element of a 1D array.
new_ar1=ar1+5
print(new_ar1)

# Multiply two 2D arrays element-wise.
ar3=np.array([[1,2,3],[4,5,6]])
ar4=np.array([[1,2,3],[4,5,6]])
mul_ar=ar3*ar4
print(mul_ar)

[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]
[[ 1  4  9]
 [16 25 36]]


In [201]:
# Indexing and Slicing
# Create a 5x5 array of integers from 1 to 25. Extract:
# The first row.
# The last column.
# A subarray of the first three rows and first two columns.
ar5=np.arange(1,26).reshape(5,5)
print(ar5)
print(ar5[0])
print(ar5[:,-1])
print(ar5[:3,:2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[1 2 3 4 5]
[ 5 10 15 20 25]
[[ 1  2]
 [ 6  7]
 [11 12]]


In [188]:
# Aggregation
# Create a 10-element array of random integers between 10 and 100. Find:
# The maximum value.
# The minimum value.
# The mean and standard deviation.
ar6=np.random.randint(10,101,10)
print(ar6)
print("max:",np.max(ar6))
print("min:",np.min(ar6))
print("mean:",np.mean(ar6))
print("std:",np.std(ar6))

[81 88 69 58 17 75 20 19 74 37]
max: 88
min: 17
mean: 53.8
std: 26.46809400013533


In [189]:
# Reshaping
# Convert a 1D array of numbers from 1 to 12 into a 3x4 matrix.
ar7=np.arange(1,13).reshape(3,4)
print(ar7)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [193]:
# Broadcasting
# Create a 3x3 matrix of ones. Add a 1D array [1, 2, 3] to each row.
ar8=np.ones((3,3),dtype=int)
print(ar8)
ar9=np.array([1,2,3])
print(ar9)
ar8=ar8+ar9
print(ar8)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
[1 2 3]
[[2 3 4]
 [2 3 4]
 [2 3 4]]


In [200]:
# Filtering
# Create a 1D array of random integers between 1 and 50. Extract all elements that are divisible by 5.
ar10=np.random.randint(1,51,25)
print(ar10)
ar10=ar10[ar10%5==0]
print(ar10)


[26 15 17 23 49 50 24  6 19 38  1 14 50 10 23 25 38 46 27 47  9 13 36 22
 38]
[15 50 50 10 25]


In [203]:
# Matrix Multiplication
# Create two 2x2 matrices and perform matrix multiplication.
# Advanced Indexing
# Given a 4x4 array, use fancy indexing to extract the diagonal elements.
a1=np.array([[1,2],[3,4]])
a2=np.array([[5,6],[1,2]])
ar11=np.dot(a1,a2)
print(ar11)
ar12=np.random.randint(1,21,16).reshape(4,4)
print(ar12)
ar13=ar12[[0,1,2,3],[0,1,2,3]]
print(ar13)


[[ 7 10]
 [19 26]]
[[20 10  3  4]
 [16  7  8  9]
 [ 2 13 13  5]
 [ 3  1 13 20]]
[20  7 13 20]


In [207]:
b=ar12[[1,0,1,0],[0,1,2,0]] #Select elements(1,0),(0,1),(1,2) and(0,0)
print(b)
b=ar12[[1,0,1, 0]][:,[0,1,2,0]]
print(b)


[16 10  8 20]
[[16  7  8 16]
 [20 10  3 20]
 [16  7  8 16]
 [20 10  3 20]]
